### ISSUE TITLE
springboot  Controller  @param  @link 无法正常使用

### ISSUE THREAD

**Issue by zzz583974851** [Earth-1610/spring-demo#25]
[代码图片](https://ftp.bmp.ovh/imgs/2021/04/acbe8cf819fd6b87.png)
[代码图片](https://ftp.bmp.ovh/imgs/2021/04/41b7343acc919ad2.png)
[代码图片](https://ftp.bmp.ovh/imgs/2021/04/507d01a143568ab5.png)

package borui.web.sys;
import borui.core.commons.utils.R;
import borui.core.errorcode.ErrorCodeEnum;
import borui.service.sys.SysFileService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
/**
 * 文件上传
 * @author chendianbo
 * @email 583974851@qq.com
 * @date 2021-04-20 16:59
 * @description //TODO
 **/
@RestController
@RequestMapping("/sys/file")
public class SysFileController {
	@Autowired
	public SysFileService sysFileService;

	/**
	 * 临时文件上传
	 * @param fileTypeCode  文件类型  {@link borui.core.errorcode.ErrorCodeEnum}
	 * @param multipartFile 文件流
	 * @param auth  是否授权，true授权为私有文件，false设置为公开文件
	 * @return
	 */
	@PostMapping("/tempUpload")
	public R upload(Long fileTypeCode,MultipartFile multipartFile, Boolean auth) {
		return R.success(sysFileService.tempSave(fileTypeCode,multipartFile,auth));
	}

}

package borui.core.errorcode;

/**
 * @author chend
 */
public enum ErrorCodeEnum {
	/**
	 * 账号相关
	 */
	ACCOUNT_OR_PASSWORD_ERROR(1000, "账号或者密码错误"),
	ip_lock(1001, "当前ip达到错误登录次数限制，已被限制登录"),
	ACCOUNT_LOCK(1002, "账号已冻结"),

	/**
	 * 文件上传
	 */
	File_UPDATE_FAILE(2000, "文件上传失败!"),
	File_ENTITY_SAVE_FAILE(2001, "SysFileEntity保存失败!"),
	FILE_ID_NOT_EXIST(2002, "文件id不存在!"),
	FILE_AUTH_ERROR(2003, "文件授权错误!");

	ErrorCodeEnum(int number, String description) {
		this.code = number;
		this.description = description;
	}

	public int code;
	public String description;

	public int getCode() {
		return code;
	}

	public String getDescription() {
		return description;
	}

}

无法正常解析这个枚举 ，yapi显示 

fileTypeCode | 否 | 0 | 文件类型  [ErrorCodeEnum]

**Comment by tangcent** [comment]
trace at: https://github.com/tangcent/easy-yapi/issues/451
