### ISSUE TITLE
kotlin 数据类的属性注释不能识别成功

### ISSUE THREAD

**Issue by LiSircxy** [Earth-1610/spring-demo#33]
![image](https://user-images.githubusercontent.com/89894908/218296784-022b041f-6804-4bdf-9b74-370b2d4ad90b.png)
当使用data class 这种方式的时候，age属性上面用行注释的时候" // "不能识别出来
![image](https://user-images.githubusercontent.com/89894908/218296838-a410cffd-f51e-4af9-a814-3d0ef426d911.png)

**Comment by tangcent** [comment]
trace at tangcent/easy-yapi#916
