### ISSUE TITLE
springboot项目application.yml   context-path配置获取不到

### ISSUE THREAD

**Issue by LiSircxy** [Earth-1610/spring-demo#35]
![image](https://user-images.githubusercontent.com/89894908/218297378-524eba89-633a-4737-a83b-0dfb2ea2a575.png)
![image](https://user-images.githubusercontent.com/89894908/218297404-73843e4a-d18f-4ce7-a4cb-02697acd5170.png)
![image](https://user-images.githubusercontent.com/89894908/218297411-fdbca2fd-b55b-4d04-944b-23cdd7dd6ac8.png)
![image](https://user-images.githubusercontent.com/89894908/218297424-c505dcb4-5889-4ae6-84a4-6d722539361e.png)
最后在postman上面url上面没有context-path配置的路径

**Comment by tangcent** [comment]
- 有没有勾选[`import_spring_properties`](https://github.com/tangcent/easy-api/blob/master/idea-plugin/src/main/resources/.recommend.easy.api.config#L196)?


- 控制台有没有输出错误日志?

**Comment by LiSircxy** [comment]
> * 有没有勾选[`import_spring_properties`](https://github.com/tangcent/easy-api/blob/master/idea-plugin/src/main/resources/.recommend.easy.api.config#L196)？
> * 控制台有没有输出错误日志?

之前没有勾选，勾选之后就好使了，能够出现了

**Comment by LiSircxy** [comment]
> 

之前没有勾选，勾选之后就好使了，能够出现了
